# Generated by Django 4.2.7 on 2024-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
