# Generated by Django 4.2.7 on 2024-04-27 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
